apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w4ar7si8b-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w4ar7si8b-python 
  name: w4ar7si8b-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w4ar7si8b-python 
